Catches instances where the file path is not readable
macadmins/nudge pull request #155
Opened 2021-03-14 06:44 UTC by bartreardon

This can occur as "FileManager.default.fileExists(atPath:..." will return true if the file exists but not necessarily if it is readable (this caught me out a couple of times)

Will return SF Symbol "applelogo" as default image and write to error log

Now on development branch instead of main (we hope)

2021-03-15 16:44 UTC, erikng requested changes

2021-03-15 16:44 UTC, erikng commented on Nudge/Utilities/Utils.swift
> +            let errorImageConfig = NSImage.SymbolConfiguration(pointSize: 200, weight: .regular)
so I think instead of doing it here, we should return a `nil`. I _think_ the code that then calls this image will bail if it's nil. If not, I'd prefer to fix it there. There are several calls where I use createImageData and in the future I might add more. Having it hardcode a default image is probably going to cause me grief down the line.

2021-03-15 21:10 UTC, bartreardon commented on Nudge/Utilities/Utils.swift
> +            let errorImageConfig = NSImage.SymbolConfiguration(pointSize: 200, weight: .regular)
The thought did cross my mind regarding hardcoding the image name. Could easily be an optional passed in with a default global as fallback or something (especially as this is the third time calling for "applelogo"). Then you could request using a specified SF Symbol by name so your call can return something expected.

The general problem I'm wanting to avoid is `NSData(contentsOf: urlPath as URL)` will return `nil` if it can't read the file contents and so will barf and crash when you unwrap it as it does in the current implementation
`let imageData:NSData = NSData(contentsOf: urlPath as URL)!`

The intent was then to say "you've asked me to return image data, I couldn't read the file, here's a default error image instead" since you're also unwrapping the return so we return "something" to keep everything happy. As an admin I'd be testing before deploying anyway, hence returning some type of broken image glyph to make it obvious something was amiss, otherwise you're looking at putting conditional logic around every call to `createImageData()` to display some default in case of `nil`.

happy to keep playing around with the implementation. The solution came about as in my project I want to request an image from a URL in addition to reading from a local file, which is more prone to breaking.

2021-03-16 13:43 UTC, erikng commented
After playing with this, I think you are right that this is the best implementation to reduce code complexity. I did play around with the various question marks, but ultimately I think showing the default apple logo is better than the previously recommended symbols.

While it won't be as blatantly clear as to why this is happening, should this happen on a user's machine, it would be even less ideal/more confusing and be a poorer user experience.

I'm merging this as-is. Thanks for the contribution.

2021-03-16 13:43 UTC, merged