Tweak minimal mode by adding required and current OS
macadmins/nudge pull request #192
Opened 2021-07-16 15:05 UTC by natewalck

This does a few things:

- Add Required and Current OS versions 
- Tweak weights/titles

Also I propose making Deferral count hidden by default in minimal mode, but with an option to enable it. The thought process is one can use minimal mode for the first N days of nudging and only switch to full mode if people are ignoring it.

Here is what it looks like with deferralCount:

<img width="1012" alt="Screen Shot 2021-07-16 at 11 02 21 AM" src="https://user-images.githubusercontent.com/867868/125968705-035a4a1e-cc1b-4500-98ed-b74320d8b075.png">

And without:
<img width="1012" alt="Screen Shot 2021-07-16 at 11 02 11 AM" src="https://user-images.githubusercontent.com/867868/125968734-e7f138d3-af3e-453f-8ad6-c66a2e9e3133.png">

It looks a lot cleaner without the deferral count, so the option to disable it would be very good to have (or even disable by default, enable by option, which is my preference).

2021-07-16 15:48 UTC, erikng commented
Can you switch to the non-debug xcworkspace and take screenshots of just simple mode?

My first inclination is to say it's busy, but I think it's because both UIs are rendering in your example.

2021-07-16 16:23 UTC, natewalck commented
Here is everything enabled:

<img width="1012" alt="Screen Shot 2021-07-16 at 12 21 27 PM" src="https://user-images.githubusercontent.com/867868/125978683-8bef3de1-8d31-476d-bfe0-b5c0193b11ab.png">

Here is without Deferred count:

<img width="1012" alt="Screen Shot 2021-07-16 at 12 22 34 PM" src="https://user-images.githubusercontent.com/867868/125978806-1dba9ca3-05cd-4ed9-9774-037495960f0c.png">

I think in Simple mode, it might even be worth hiding  "Days remaining" by default.

2021-07-16 16:38 UTC, erikng commented
I don't use simple mode, so would like anyone who is to chime in on these changes as it does remove UX.

2021-07-16 16:47 UTC, erikng requested changes

2021-07-16 16:47 UTC, erikng commented on Nudge/Preferences/DefaultPreferencesNudge.swift
> +//let hideDeferralCount = userInterfaceProfile?["hideDeferralCount"] as? Bool ?? userInterfaceJSON?.hideDeferralCount ?? false
unfinished?

2021-07-16 16:47 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                            .font(.title3)
why did you move to title3? That may be why I dislike the change

also see my comment on standard mode

2021-07-16 16:47 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                        .font(.title3)
IMO should be title2 to stay consistent with the other textfields. Standard mode keeps the same font weight for all of these UI fields

2021-07-16 16:47 UTC, erikng commented on Nudge/UI/StandardMode/LeftSide.swift
> +                if !Utils().hideDeferralCountEnabled() {
`hideDeferralCountEnabled` think this should be rewritten. you have a negative key with a positive state. Perhaps you should change this instead to `showDefferalCount`? in the actual preference key and then the call can just be

`if Utils().showDeferralCount() {`.

2021-07-16 16:47 UTC, erikng commented on Nudge/Utilities/Utils.swift
> +    func hideDeferralCountEnabled() -> Bool {
do we _need_ a cli option for this? I think preferences are fine for this particular UX change.

2021-07-16 16:47 UTC, erikng commented on Nudge/Utilities/Preferences.swift
> +func hideDeferralCount() -> Bool {
If you remove the CLI functionality, we can remove double function stuff.

2021-07-16 16:47 UTC, erikng commented on Nudge/Utilities/Utils.swift
> +
Good old Xcode adding padding on this line because you probably accidentally hovered your mouse on it. ;)

2021-07-16 17:54 UTC, natewalck commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                        .font(.title3)
In Simple mode, title2 looks a little big, but maybe it's fine?. Here is title2 vs title3 for all of them:

title2:

<img width="1012" alt="Screen Shot 2021-07-16 at 1 54 09 PM" src="https://user-images.githubusercontent.com/867868/125989323-b8585453-64b3-47ef-9a23-9b58852f7059.png">

title3:

<img width="1012" alt="Screen Shot 2021-07-16 at 1 53 51 PM" src="https://user-images.githubusercontent.com/867868/125989342-42b54a11-1818-486f-86a9-48072b9449cc.png">

2021-07-16 17:55 UTC, natewalck commented on Nudge/UI/StandardMode/LeftSide.swift
> +                if !Utils().hideDeferralCountEnabled() {
I had it that way to begin with, but I can flip it again.

2021-07-16 18:39 UTC, natewalck commented
This should be ready for review again.

2021-07-16 19:17 UTC, macbm commented
We only use Simple Mode in our environment, and we like the changes Nate is proposing.
It would be great to have the options to show/hide "Days remaining to update", "Require OS Version" & "Current OS Version" if possible for better control/customization.

2021-07-16 19:59 UTC, w0de commented
+1 to @macbm's comments

This is a good change for our use of simple mode. Presently we overload the "More Info" button to further inform users, but that isn't device-state specific. This strikes a good balance and will probably have a positive impact on user touchpoints. As it is now, we would use this.

I have an aesthetic nitpick: 

* Is a bit busy
* the mismatch between bold/not bold for day/deferral values & OS version values contributes to this
* three buttons each of their own style and alignment contributes to this

Would perhaps a [popover view](https://developer.apple.com/documentation/swiftui/path/popover(ispresented:attachmentanchor:arrowedge:content:)) allow displaying further information in simple mode more elegantly? Perhaps an option for configuring `More Info` in lieu of setting an `aboutUpdateURL` - or with this URL configuring button inside the popover instead.

2021-07-23 14:47 UTC, natewalck commented
> We only use Simple Mode in our environment, and we like the changes Nate is proposing.
> It would be great to have the options to show/hide "Days remaining to update", "Require OS Version" & "Current OS Version" if possible for better control/customization.

We discussed this in Slack a little and for now we are going to try to settle on a standard simple mode UI that has only actionable information for the end user. In this case, its the required version of macOS and how many days they have left to update. The other information is a kind of noise by itself and having all 4 makes Simple mode not so simple. 

I'm proposing the current diff is the new default and then we can talk about making them a preference or something like that.

2021-07-23 16:53 UTC, natewalck commented
For bonus points, added the device info button to simple mode: 
<img width="1012" alt="Screen Shot 2021-07-23 at 12 53 08 PM" src="https://user-images.githubusercontent.com/867868/126815647-7bafe72b-0bed-4f84-9d42-293e8b8b9a30.png">

2021-07-23 18:47 UTC, natewalck commented
Completely and utterly changed my mind here about showing required OS version. People have no clue what they are on or what is required. Maybe this can be added to the `?` long term for inquisitive minds, but for 98% of everyone it is not useful information as we are only showing this screen if they are indeed out of date.

Here is the latest:
<img width="1012" alt="Screen Shot 2021-07-23 at 2 47 14 PM" src="https://user-images.githubusercontent.com/867868/126827716-0c66297a-441a-4770-b17e-0437c1a05bdd.png">


PS: Aligning stuff sucks. The more info button keeps moving 🙄

2021-07-23 20:25 UTC, erikng commented
I like this.

2021-07-26 15:11 UTC, natewalck commented
Need review on this.

2021-07-28 16:35 UTC, natewalck commented
Alright, this is rebased to Development and I confirmed it ran:

<img width="1012" alt="Screen Shot 2021-07-28 at 12 34 16 PM" src="https://user-images.githubusercontent.com/867868/127361663-74e33e58-34ba-4a9a-bfbe-f8d9de42d3d1.png">

2021-07-28 19:28 UTC, erikng requested changes

2021-07-28 19:28 UTC, erikng commented on Nudge/Preferences/PreferencesStructure.swift
> +    var forceFallbackLanguage, forceScreenShotIcon, showDeferralCount: Bool?
Nit but all of the keys are alphabetical before this change. Can you move it down to L370?

2021-07-28 20:09 UTC, natewalck commented
I *think* we are good now at least on Big Sur.

<img width="1012" alt="Screen Shot 2021-07-28 at 4 08 05 PM" src="https://user-images.githubusercontent.com/867868/127388834-d17ac450-b9dd-4a7d-baea-10fe9ef242aa.png">

<img width="1012" alt="Screen Shot 2021-07-28 at 4 08 14 PM" src="https://user-images.githubusercontent.com/867868/127388839-376d6c0a-4d85-4277-b4e7-5f30590f93cf.png">

2021-07-29 13:30 UTC, erikng requested changes

2021-07-29 13:30 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                    Text("Days Remaining To Update".localized(desiredLanguage: getDesiredLanguage()))
The original code is `Days Remaining To Update:` so this will break the localization. Also this `Text(` call needs to come before the `if self.daysRemaining` part so the days remaining will render correctly.

I see in the screenshots you flipped it, but that's going to unfortunately break a lot of other things when not in English language.

2021-07-29 13:30 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> -                // Deferred Count
You got rid of the Deferral Count logic, but added the `showDeferralCount` key. This should be brought back in and mimic what you did on `LeftSide.swift`

As a note, I think maybe v2 of this should create a new key like `hideElements` and it's an array so we don't have so many `showBlah` stuff.

2021-07-29 13:30 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                HStack(spacing: 3.5) {
Will be interesting to see how this spacing plays out with conditionally showing/hiding deferral count.

2021-07-29 13:30 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                .padding(.bottom, 2)
Will be interesting to see how this padding plays out with conditionally showing/hiding deferral count.

2021-07-29 13:30 UTC, erikng commented on Nudge/UI/SimpleMode/SimpleMode.swift
> +                Spacer()
Will be interesting to see how this spacer plays out with conditionally showing/hiding deferral count.

2021-07-29 15:01 UTC, natewalck commented on Nudge/UI/SimpleMode/SimpleMode.swift
> -                // Deferred Count
Adding deferral count will make it look very cluttered like the previous screenshots showed. Do we want it to be an option if it leads to poor UI?

2021-07-29 15:24 UTC, natewalck commented
Alright, by taking the `?` button out of the centered vstack, we can avoid the showDeferralCount being enabled/disabled impacting the vertical spacing on the `?`. This allows us to tweak the location of the `?` independently of the other VStacks.

2021-07-29 15:25 UTC, natewalck commented
I did just notice the button location changes when deferral count is enable or disabled -_-  Guess I'll figure that out now.

<img width="1012" alt="Screen Shot 2021-07-29 at 11 21 23 AM" src="https://user-images.githubusercontent.com/867868/127519872-59ebbcca-0656-4e04-a24b-1b5ec259bf30.png">
<img width="1012" alt="Screen Shot 2021-07-29 at 11 20 50 AM" src="https://user-images.githubusercontent.com/867868/127519870-0a40f622-f29f-47fb-9e0f-c9727fe5220b.png">

2021-07-29 16:30 UTC, natewalck commented
This is really dumb, but it works :D Button doesn't move at all (I tried various other combinations of Spacer() and padding, but nothing worked quite right).

<img width="1012" alt="Screen Shot 2021-07-29 at 12 29 02 PM" src="https://user-images.githubusercontent.com/867868/127529934-fd3627fb-51c3-4d53-98c8-b808ac99f183.png">
<img width="1012" alt="Screen Shot 2021-07-29 at 12 28 51 PM" src="https://user-images.githubusercontent.com/867868/127529935-c645f95c-1134-4bce-84bb-a6034c4f5c33.png">

2021-08-03 14:36 UTC, erikng approved these changes

2021-08-03 14:36 UTC, merged