Add Russian locatlization
macadmins/nudge pull request #299
Opened 2022-01-30 13:37 UTC by adipierro

2022-01-31 15:40 UTC, erikng requested changes

2022-01-31 15:40 UTC, erikng commented on ru.lproj/Localizable.strings
> +"Username:" = "Username:";
Did you forget to do this one?

2022-02-01 17:14 UTC, adipierro commented on ru.lproj/Localizable.strings
> +"Username:" = "Username:";
Hi. 'Username' in Russian might be too big for that window – 'Имя пользователя'. I considered using 'Логин', but it's slang'ish.

2022-02-02 16:40 UTC, erikng commented on ru.lproj/Localizable.strings
> +"Username:" = "Username:";
If you'd like, push a change with the non slang version and I can cut a test release on this PR to try it.

2022-02-02 16:53 UTC, adipierro commented on ru.lproj/Localizable.strings
> +"Username:" = "Username:";
Okay.

2022-02-03 18:20 UTC, erikng commented
I built it yesterday https://github.com/macadmins/nudge/runs/5043590338?check_suite_focus=true

and sorry I'm very sick yesterday and today so will be slow to respond.

2022-02-04 18:49 UTC, erikng commented
<img width="1012" alt="Screen Shot 2022-02-04 at 12 48 45 PM" src="https://user-images.githubusercontent.com/5685016/152585940-2a856057-82e5-432d-84be-f946943c8021.png">
<img width="1012" alt="Screen Shot 2022-02-04 at 12 48 55 PM" src="https://user-images.githubusercontent.com/5685016/152585953-7b5f9bb7-3a6a-48fa-8043-3694c8ffc52a.png">

maybe fix `(Demo Mode)`?

2022-02-06 17:35 UTC, merged