Added Norwegian localization
macadmins/nudge pull request #314
Opened 2022-02-17 12:15 UTC by gustaf08

2022-02-17 12:55 UTC, erikng commented
I don't think this will work as is because it was likely created outside of Xcode. The Xcode project doesn't know where to add it to the app bundle. 

Typically if you look at other PRs for languages, two files are modified.

2022-02-17 14:16 UTC, gustaf08 commented
Hopefully its fixed now.

2022-02-17 15:38 UTC, erikng requested changes

2022-02-17 15:38 UTC, erikng commented on Nudge.xcodeproj/project.pbxproj
> +				nb,
Where did this come from?

2022-02-18 08:24 UTC, gustaf08 commented
Sorry am a bit new to this, have updated it.

2022-02-22 14:36 UTC, erikng commented
<img width="1012" alt="Screen Shot 2022-02-22 at 8 36 33 AM" src="https://user-images.githubusercontent.com/5685016/155154065-a1df5ad5-8ec3-47d4-badb-e81927f64650.png">
<img width="1012" alt="Screen Shot 2022-02-22 at 8 36 24 AM" src="https://user-images.githubusercontent.com/5685016/155154076-43c1650b-2cf3-4acd-98d4-47b40a697587.png">
Looks good to me

2022-02-22 14:37 UTC, merged