WIP: Add remediation for BTM corruption if users are upgrading from 1.1.12.81501
macadmins/nudge pull request #519
Opened 2023-10-06 22:03 UTC by rickheil

Preinstall: checks if a problematic version (81501) is installed, and touches a file if so.
Postinstalls: same logic in both, looks for the touch file and if found runs the remediation.

Currently getting an "illegal byte sequence" error as I wrote this assuming /bin/sh and not ZSH - will continue working on this in Slack after dinner.

All the credit to @kevinmcox and @tuxudo for finding the BTM plist is editable and figuring out the PlistBuddy pieces.

2023-10-07 00:23 UTC, rickheil commented
Ready for testing!

2023-10-07 00:41 UTC, rickheil-samsara commented
For linking purposes: fixes https://github.com/macadmins/nudge/issues/515

2023-10-07 00:53 UTC, kevinmcox commented
Thanks for putting this all together @rickheil!

2023-10-07 03:32 UTC, erikng commented
I have a theory. What if we ran the nudge uninstall SMApp cli flag instead? Would it remove the same keys from that file?

2023-10-07 03:33 UTC, erikng commented
Also you need to do this on the dev branch not main. I haven't merged the other code yet into main.

2023-10-07 05:14 UTC, kevinmcox commented
Erik, is that the --unregister flag?

I tried that one yesterday and it didn't work.

That said, I can't promise I tried it in all combinations of scenarios, so definitely worth trying again after installing 1.1.13.

2023-10-07 22:36 UTC, natewalck requested changes
Looking pretty good.

2023-10-07 22:36 UTC, natewalck commented on build_assets/postinstall-app
> +    echo "Error: unable to locate a BTM plist, no remediation occurred. Does this OS support BTM features?"
If we are doing nothing else in the postinstall, we should exit here.

2023-10-07 22:36 UTC, natewalck commented on build_assets/postinstall-app
> +  while $remediate; do
Since we are exiting early above, we can get rid of the while altogether and flatten this to a if/elif/else statement.

2023-10-07 22:36 UTC, natewalck commented on build_assets/postinstall-app
> +  rm /private/var/tmp/nudge_remediate
If we flatten this, the only negative is we may need to `rm` this above around line 32 as well. Flattening the loops seems worth it for readability.

2023-10-07 22:37 UTC, natewalck commented on build_assets/postinstall-suite
> +    remediate=True
Come to think of it, if we are exiting on the else here, we don't need to set this variable at all.

2023-10-07 22:39 UTC, natewalck commented on build_assets/postinstall-app
> +    remediate=True
Come to think of it, if we are exiting on the else around line 31, we don't need to set this variable at all.

2023-10-09 16:27 UTC, tuxudo commented
Do you have a v4 or v8 on disk? It would appear the v3 is from a very early version of Ventura

2023-10-09 17:11 UTC, erikng commented
I no longer think this option is viable and am tempted to close the PR. This change is going to require full disk access.

When I first saw the PR, I thought it was a security issue in that if you can delete, you can add. In my testing, accessing this file on a terminal without FDA gives this error.

```
/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v8.btm: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=257 "The file "BackgroundItems-v8.btm" couldn't be opened because you don't have permission to view it." UserInfo={NSFilePath=/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v8.btm, NSUnderlyingError=0x600003548000 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}})
```

2023-10-09 17:13 UTC, natewalck commented
Thats great then. Apple's edge case here is going to cause a bit of...pain.

2023-10-09 17:53 UTC, closed without merging