Update german (de) localization
macadmins/nudge pull request #648
Opened 2024-08-21 06:56 UTC by northalpha

Using informal speach like Apple does talking about their customer and their products

This will also will fix #646

2024-08-21 07:22 UTC, AirBookMac requested changes
dein Mac -> deinen Mac

2024-08-21 07:22 UTC, AirBookMac commented on Localizable.xcstrings
> +            "value" : "Um sicherzustellen, dass die IT dein Mac ordnungsgemäß schützen kann, ist ein aktueller Mac erforderlich.\n\nWenn Du kein Ersatzgerät erhalten hast, verlierst Du ggf. den Zugri
deinen Mac

2024-08-21 07:22 UTC, AirBookMac commented on Localizable.xcstrings
> +            "value" : "Ein vollständig aktualisierter Mac ist erforderlich, um sicherzustellen, dass die IT-Abteilung dein Mac effektiv schützen kann.\n\nWenn du dein Mac nicht aktualisierst, verlier
die IT-Abteilung dein Mac effektiv -> die IT-Abteilung deinen Mac effektiv

2024-08-21 07:22 UTC, AirBookMac commented on Localizable.xcstrings
> +            "value" : "Bitte aktualisiere dein Mac, um dieses Programm zu verwenden."
Bitte aktualisiere dein Mac -> Bitte aktualisiere deinen Mac

2024-08-21 08:05 UTC, northalpha commented on Localizable.xcstrings
> +            "value" : "Um sicherzustellen, dass die IT dein Mac ordnungsgemäß schützen kann, ist ein aktueller Mac erforderlich.\n\nWenn Du kein Ersatzgerät erhalten hast, verlierst Du ggf. den Zugri
fixed

2024-08-22 08:48 UTC, AirBookMac reviewed
german language looks fine

2024-08-22 16:34 UTC, merged